#!/usr/bin/env python3
"""Create a COCO ground-truth JSON from an official VisDrone2019-DET split.

Image IDs intentionally follow Ultralytics JSON export behavior: a numeric filename stem
is converted to ``int``; otherwise the filename stem itself is used. This keeps the ground
truth IDs aligned with ``predictions.json`` generated by ``model.val(save_json=True)``.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Optional, Tuple, Union

from PIL import Image
from tqdm import tqdm

NAMES = [
    "pedestrian",
    "people",
    "bicycle",
    "car",
    "van",
    "truck",
    "tricycle",
    "awning-tricycle",
    "bus",
    "motor",
]


def image_id_from_path(path: Path) -> Union[int, str]:
    """Match Ultralytics' image ID convention used by detection JSON export."""
    return int(path.stem) if path.stem.isnumeric() else path.stem


def clip_xywh(
    x: float, y: float, w: float, h: float, image_w: int, image_h: int
) -> Optional[Tuple[float, float, float, float]]:
    """Clip a VisDrone xywh box to image bounds and drop empty boxes."""
    x1 = min(max(x, 0.0), float(image_w))
    y1 = min(max(y, 0.0), float(image_h))
    x2 = min(max(x + w, 0.0), float(image_w))
    y2 = min(max(y + h, 0.0), float(image_h))
    clipped_w = x2 - x1
    clipped_h = y2 - y1
    if clipped_w <= 0 or clipped_h <= 0:
        return None
    return x1, y1, clipped_w, clipped_h


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--split-dir", required=True, type=Path, help="e.g. VisDrone2019-DET-val"
    )
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    images_dir = args.split_dir / "images"
    annotations_dir = args.split_dir / "annotations"
    if not images_dir.is_dir():
        raise FileNotFoundError(f"Images directory not found: {images_dir}")

    image_paths = sorted(
        p
        for p in images_dir.iterdir()
        if p.suffix.lower() in {".jpg", ".jpeg", ".png", ".bmp"}
    )

    coco = {
        "info": {
            "description": "VisDrone2019-DET converted to COCO for APsmall evaluation"
        },
        "licenses": [],
        "categories": [
            {"id": i + 1, "name": name, "supercategory": "object"}
            for i, name in enumerate(NAMES)
        ],
        "images": [],
        "annotations": [],
    }
    annotation_id = 1
    for image_path in tqdm(image_paths, desc="COCO conversion"):
        with Image.open(image_path) as image:
            width, height = image.size
        image_id = image_id_from_path(image_path)
        coco["images"].append(
            {
                "id": image_id,
                "file_name": image_path.name,
                "width": width,
                "height": height,
            }
        )
        annotation_path = annotations_dir / f"{image_path.stem}.txt"
        if not annotation_path.exists():
            continue
        for line in annotation_path.read_text(encoding="utf-8-sig").splitlines():
            fields = line.strip().rstrip(",").split(",")
            if len(fields) < 6:
                continue
            try:
                x, y, w, h = map(float, fields[:4])
                category = int(float(fields[5]))
            except ValueError:
                continue
            if not 1 <= category <= 10 or w <= 0 or h <= 0:
                continue
            box = clip_xywh(x, y, w, h, width, height)
            if box is None:
                continue
            x, y, w, h = box
            coco["annotations"].append(
                {
                    "id": annotation_id,
                    "image_id": image_id,
                    "category_id": category,
                    "bbox": [x, y, w, h],
                    "area": w * h,
                    "iscrowd": 0,
                    "segmentation": [],
                }
            )
            annotation_id += 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(coco, ensure_ascii=False), encoding="utf-8"
    )
    print(
        f"wrote {len(coco['images'])} images and "
        f"{len(coco['annotations'])} annotations to {args.output}"
    )


if __name__ == "__main__":
    main()
